// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chats.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChatWith = `-- name: CreateChatWith :one
INSERT INTO chats (id, created_at, updated_at, chat_by, chat_with)
VALUES (
    gen_random_uuid (), NOW(), NOW(), $1, $2
)
RETURNING id, created_at, updated_at, chat_by, chat_with
`

type CreateChatWithParams struct {
	ChatBy   uuid.UUID
	ChatWith uuid.UUID
}

func (q *Queries) CreateChatWith(ctx context.Context, arg CreateChatWithParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChatWith, arg.ChatBy, arg.ChatWith)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChatBy,
		&i.ChatWith,
	)
	return i, err
}

const getChatById = `-- name: GetChatById :one
SELECT id, created_at, updated_at, chat_by, chat_with FROM chats WHERE id = $1
`

func (q *Queries) GetChatById(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatById, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChatBy,
		&i.ChatWith,
	)
	return i, err
}

const getChatsByUser = `-- name: GetChatsByUser :many
SELECT id, created_at, updated_at, chat_by, chat_with FROM chats WHERE chat_by = $1
`

func (q *Queries) GetChatsByUser(ctx context.Context, chatBy uuid.UUID) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getChatsByUser, chatBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChatBy,
			&i.ChatWith,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
