// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, created_at, updated_at, body, chat_id, sender_id, receiver_id)
VALUES (
    gen_random_uuid (),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, body, chat_id, sender_id, receiver_id
`

type CreateMessageParams struct {
	Body       string
	ChatID     uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.Body,
		arg.ChatID,
		arg.SenderID,
		arg.ReceiverID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.ChatID,
		&i.SenderID,
		&i.ReceiverID,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1 AND chat_id = $2
`

type DeleteMessageParams struct {
	ID     uuid.UUID
	ChatID uuid.UUID
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, arg.ID, arg.ChatID)
	return err
}

const getMessageById = `-- name: GetMessageById :one
SELECT id, created_at, updated_at, body, chat_id, sender_id, receiver_id FROM messages WHERE id = $1
`

func (q *Queries) GetMessageById(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageById, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.ChatID,
		&i.SenderID,
		&i.ReceiverID,
	)
	return i, err
}

const getMessageWhereChatAndUser = `-- name: GetMessageWhereChatAndUser :one
SELECT id, created_at, updated_at, body, chat_id, sender_id, receiver_id FROM messages WHERE chat_id = $1 and sender_id = $2
`

type GetMessageWhereChatAndUserParams struct {
	ChatID   uuid.UUID
	SenderID uuid.UUID
}

func (q *Queries) GetMessageWhereChatAndUser(ctx context.Context, arg GetMessageWhereChatAndUserParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageWhereChatAndUser, arg.ChatID, arg.SenderID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.ChatID,
		&i.SenderID,
		&i.ReceiverID,
	)
	return i, err
}

const getMessagesByChatId = `-- name: GetMessagesByChatId :many
SELECT id, created_at, updated_at, body, chat_id, sender_id, receiver_id FROM messages WHERE chat_id = $1
`

func (q *Queries) GetMessagesByChatId(ctx context.Context, chatID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChatId, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.ChatID,
			&i.SenderID,
			&i.ReceiverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
